### ISSUE TITLE
I want to learn to use your model, but due to my current computer performance limitations, I am not able to train a model, so ask me if you can send me your trained model.

### ISSUE THREAD

**Issue by BobiLoveDier** [liangstein/Chinese-speech-to-text#2]
Thanks

**Comment by liangstein** [comment]
https://www.dropbox.com/s/anvw5x7bmjsm94u/listen_model.chk?dl=0

**Comment by Alvin2580du** [comment]
Thank you

**Comment by zhaowz** [comment]
use your code and load your model but have error, can you help me?
Traceback (most recent call last):
  File "/home/zhaozhe/tensorflow-gpu_zz131/deeplearning/speech_proj/Chinese-speech-to-text/speech_to_text.py", line 61, in <module>
    model.load_weights(DIR+"/listen_model.chk");
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2652, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/keras/engine/topology.py", line 3176, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/keras/engine/topology.py", line 3070, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/zhaozhe/python27/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: axes don't match array

**Comment by liangstein** [comment]
are you using the same version of python and keras?

2018-03-02 17:02 GMT+08:00 zhaowz <notifications@github.com>:

**Comment by nathphoenix** [comment]
Hi @liangstein @Alvin2580du  please can you help me with the pretrained model, tried to download from google drive but not responding, wanted to test the output before training, 
i have the error below stating the pretrain model is not available

**Comment by liangstein** [comment]
> 

https://www.dropbox.com/s/ujiardfgl2z51ya/listen_model.chk?dl=0

**Comment by nathphoenix** [comment]
Thank you so much, I was able to get the output which is the same with yours @liangstein ,
please one last thing, can you please help me with the format of the dataset so it can help me in creating my own dataset.
A screenshot of tour dataset will be very helpful.

**Comment by liangstein** [comment]
> 
This was done too long ago, I forget the details. If you can find the Chinese audio dataset I used in this repositary, it will not be hard to find out the dataset format.
